### ISSUE TITLE
[RPI] jackd: symbol lookup error: jackd: undefined symbol: jackctl_server_create2

### ISSUE THREAD

**Issue by workino** [jackaudio/jack2#571]
Hello,
i compiled Jackd2 V. 1.9.14 on rabian 10 but i'm getting this error: 

```
jackdmp 1.9.14
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2019 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
jackd: symbol lookup error: jackd: undefined symbol: jackctl_server_create2 ```

There is a way to solve or the version 1.9.14 is in to an too early stage?

Regards
Gabriele

**Comment by falkTX** [comment]
Likely mix of self-built binaries with stuff from the distribution.
Try deleting the old contents for libjack and libjackserver, then reinstalling jack once again

**Comment by DinkDonk** [comment]
Raspberry Pi OS, even the Lite version, has jack libraries installed by default.  
I suspect this is the case with rabian as well.  
You can check if there are some latent jack stuff on the system by searching the installed packages:

```bash
$ apt list --installed | grep jack
```

Most likely you will get more that 0 hits on that search.  
Remove every `jack` package by running this command:

```bash
$ sudo apt remove '*jack*'
```

If you built jack with `--prefix /usr`, everything should now work as intended.  
You can remove the jack apt packages before or after you build jack from source – it doesn't matter.

**Comment by aardvarkk** [comment]
I'm getting this error on MX Linux when trying to install and run v1.9.18 from source. I tried removing every package I had with `jack` in the name, then recompiling and reinstalling the built binaries, but am still getting the same error. Not sure where to go from here.

**Comment by arthurc2000** [comment]
I have similar issue and the following solve the problem.
It looks like you have an old partial installation in the sytem..

./waf configure --prefix=/usr
./waf install 

Maybe a better install script should detect and warn about the old stuff first.

**Comment by falkTX** [comment]
`--prefix=/usr` will produce bad results for debian based distributions.
It is questionable if this is a jack2 issue

pull requests to try to handle this better are welcome.

**Comment by arthurc2000** [comment]
I am using the Yocto distribution, which have different binary path and I have to install manually.
Probably just leave this as a FAQ.

Basically, let the user to locate the old stuff first and remove them manually is better.
# whereis jackd
# whereis libjack.so

**Comment by ndmgrphc** [comment]
Any idea on how to get the manual build of jackd to work with ffmpeg on apt?  I need ffmpeg but I don't need ffmpeg jack support -- curious if anyone here happens to know how to build ffmpeg without jackd support so I can build my own jackd without dbus.

**Comment by worikgh** [comment]
I get this error too.

After `./waf build` I run `./build/jackd`

```
~/jack2 $ build/jackd
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
build/jackd: symbol lookup error: build/jackd: undefined symbol: jackctl_server_create2
```

**Comment by nedko** [comment]
@worikgh: you have older version of a jack library dangling in your system. Cleanup and install again. Also check ldconfig
